version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    
    working_directory: ~/kid-bank

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:

      - checkout

      - restore_cache:
          key: kid-bank-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: kid-bank-{{ checksum "pom.xml" }}
      
      - run: mvn package
      
      - store_test_results:
          path: target/surefire-reports

      - codecov/upload:
           ile: {{ coverage_report_filepath }}
