version: 2.1

jobs:
  build:

    working_directory: ~/kid-bank

    docker:
      - image: circleci/openjdk:8u131-jdk

    steps:

      - checkout

      - restore_cache:
          key: kid-bank-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: kid-bank-{{ checksum "pom.xml" }}
      
      - run: ./mvnw package
      
      - store_test_results:
          path: target/surefire-reports

      - run:
          command: |
            bash <(curl -s https://codecov.io/bash)   -f target/site/jacoco/jacoco.xml   -n ${CIRCLE_BUILD_NUM}   -t ${CODECOV_TOKEN}   -F

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
          context: shared_ctx



